[package]
name = "protobuf_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = "3.0.0-alpha.2"

[build-dependencies]
protobuf-codegen-pure = "3.0.0-alpha.2"